stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  BASE_URL: "https://your-stage-url.com"
  HEADLESS: "true"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/

build:
  stage: build
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" && $CI_PIPELINE_SOURCE == "push"
      when: always
  image: maven:3.9-eclipse-temurin-17
  before_script:
    - mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI ``-Dexec.args=install --with-deps chromium`` -q
  script:
    - mvn clean compile -pl core,ui -q
  tags:
    - seo-staging-shell

ui-tests:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
  image: maven:3.9-eclipse-temurin-17
  before_script:
    - mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI ``-Dexec.args=install --with-deps chromium`` -q
  script:
    - mvn test -pl ui ``-Dheadless=$HEADLESS`` ``-Dbase.url=$BASE_URL`` -q
  artifacts:
    paths:
      - ui/target/allure-results/
    expire_in: 30 days
  tags:
    - seo-dev-shell

api-tests:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
  image: maven:3.9-eclipse-temurin-17
  script:
    - mvn test -pl api ``-Dbase.url=$BASE_URL`` -q
  artifacts:
    paths:
      - api/target/allure-results/
    expire_in: 30 days
