services:
  ui-tests:
    build: .
    volumes:
      - ./allure-results:/app/ui/target/allure-results
    environment:
      - base.url=${BASE_URL:-http://localhost:3000}
      - headless=true
      - env=${TEST_ENVIRONMENT:-stage}
    command: >
      sh -c "mvn test -pl ui ``-Dheadless=true` ``-Dbase.url=$${BASE_URL} -q"

  api-tests:
    build: .
    volumes:
      - ./allure-results:/app/api/target/allure-results
    environment:
      - base.url=${API_BASE_URL:-http://localhost:3000}
    command: >
      sh -c "mvn test -pl api ``-Dbase.url=$${API_BASE_URL} -q"
